language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose docker-compose-build.yaml build --parallel
  - docker tag reverseproxy freeborniwarri/reverseproxy:v1
  - docker tag udagram-frontend freeborniwarri/udagram-frontend:v1
  - docker tag udagram-api-feed freeborniwarri/udagram-api-feed:v1
  - docker tag udagram-api-user freeborniwarri/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push freeborniwarri/reverseproxy:v1
  - docker push freeborniwarri/udagram-frontend:v1
  - docker push freeborniwarri/udagram-api-feed:v1
  - docker push freeborniwarri/udagram-api-user:v1


# safelist
branches:
  only:
  - main