kind: Secret 
apiVersion: v1 
metadata:
  name: aws-secret 
data:
  # Configuration values can be set as key-value properties
  aws_access_key_id: QUtJQVhMVkVPNVpJS09STDI1VlY=
  aws_secret_access_key: aEFndDVzeVU3ZGJTaWhRZ3Q5cERyWFNETE93TG1yZ1d6VENuQkUvcA==