apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed-app
  labels:
    app: backend-feed-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed-app
  template:
    metadata:
      labels:
        app: backend-feed-app
    spec:
      containers:
      - name: udagram-api-feed
        image: freeborniwarri/udagram-api-feed:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:  
          - secretRef:
              name: env-secret
          - secretRef:
              name: aws-secret
          - configMapRef:
              name: env-configmap